# Generated by Django 4.1 on 2022-10-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discout',
            new_name='discount',
        ),
    ]
