# Generated by Django 4.1 on 2022-08-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
